Playlist_maker sprint 12
agolyud/YP_PlayList pull request #5
Opened 2023-04-05 14:39 UTC by agolyud

2023-04-07 01:03 UTC, NoDopezzz requested changes

2023-04-07 01:03 UTC, kirillNay commented on app/src/main/java/com/example/yp_playlist/SearchActivity.kt
> +    lateinit var buttonClear: Button
⏫ Обрати внимание на установку модификаторов доступа. Данные переменные используются только внутри `SearchActivity`, поэтому стоит сделать их `private`

2023-04-07 01:03 UTC, kirillNay commented on app/src/main/java/com/example/yp_playlist/SearchActivity.kt
> +            historyList.visibility = View.VISIBLE
⚠️ Согласно условию задачи показ истории поиска должен происходить при фокусе на поле ввода

2023-04-07 01:03 UTC, kirillNay commented on app/src/main/java/com/example/yp_playlist/SearchActivity.kt
> +            historyList.visibility = View.VISIBLE
⏫ Показ истории должен осуществляться в при следующих условиях:
- поле ввода находится в фокусе
- текстовое поле пустое
- история поиска не пустая

Поэтому проверять достоверность этих условий имеет смысл в следующих сценариях:
- изменился фокус на поле ввода - установка `OnFocusChangeListener` на `EditText`
- изменился текст в поле ввода - переопределение метода `onTextChanged` в `TextWatcher`

_Подсказка: при нажатии на кнопку крестика происходит очистка поля ввода через вызов метода `text.clear()`, который вызовет метод `onTextChanged` в `TextWatcher`_

Чтобы упростить логику показа истории предлагаю вынести ее в отдельный метод с проверкой всех условий и обновлении элементов в адаптере. Вызываться этот метод будет в описанных выше сценариях

2023-04-07 01:03 UTC, kirillNay commented on app/src/main/java/com/example/yp_playlist/SearchActivity.kt
> +            historyTracks = searchHistory.tracksHistoryFromJson() as ArrayList<Track>
⚠️ Стоит также обработать сценарий, когда текст в поле ввода был очищен вручную, а не через кнопку крестика

2023-04-07 01:03 UTC, kirillNay commented on app/src/main/java/com/example/yp_playlist/SearchHistory.kt
> +
⚠️ Существует большое количество треков с одинаковыми названиями. Поэтому вместо проверки по полю `trackName` стоит проверять по новому полю `trackId` - идентификатору трека в системе Itunes.
Если возникнут вопросы, обратись к условию задачи **"История поиска"**

2023-04-07 01:03 UTC, kirillNay commented on app/src/main/java/com/example/yp_playlist/SearchActivity.kt
> +    override fun onResume() {
⏫ Для обеспечение более качественного и своевременного способа синхронизации элементов истории на экране и элементов истории в `SharedPreference` стоит использовать слушатель изменений, который устанавливается с помощью `registerOnSharedPreferenceChangeListener`. 

Главное, помнить об [особенности слушателя](https://developer.android.com/reference/android/content/SharedPreferences#registerOnSharedPreferenceChangeListener(android.content.SharedPreferences.OnSharedPreferenceChangeListener)) в том, что он сохраняется в SharedPreference как мягкая ссылка. Это значит, что если передавать слушатель в качестве анонимной реализации интерфейса без его сохранения, то через какое-то время он уничтожится.

2023-04-07 01:03 UTC, kirillNay commented on app/src/main/java/com/example/yp_playlist/SearchHistory.kt
> +    fun addTrack(track: Track, position: Int) {
⏫ Аргумент `position` не используется в методе `addTrack`, поэтому его стоит удалить и зря не передавать

2023-04-07 01:03 UTC, kirillNay commented on app/src/main/java/com/example/yp_playlist/SearchActivity.kt
> +            historyList.visibility = View.INVISIBLE
⏫ Использование списка `List` - класса Kotlin дает больше гибкости и оптимизации использования, чем стандартный `ArrayList`, поэтому рекомендуется использовать именно его.

Вместо каста `List<Track>` в `ArrayList<Track>` стоит список треков внутри адаптера также сделать `List<Track>`

2023-04-07 01:03 UTC, kirillNay commented on app/src/main/java/com/example/yp_playlist/SearchHistory.kt
> +        if (existingTrackIndex != -1) {
⏫ Можно воспользоваться крутой функцией котлина - any, которая может проверить, есть ли хоть один элемент в списке подходящий заданному условию.
Вот пример ее использования:

```
data class Track(
   val author: String,
   val title: String
)
val tracks = listOf(Track("Nirvana", "Smells Like Teen Spirit"), Track("Jay Z", "99 Problems"), Track("The Beatles",  "Hey Jude"))
val isNirvana = tracks.any { it.author ==  "Nirvana"}
```

2023-04-07 01:03 UTC, kirillNay commented on app/src/main/java/com/example/yp_playlist/TrackAdapter.kt
> +        if (position < tracksHistory.size) {
⏫ `TrackAdapter` является адаптером для работы с определенным списком треков. Т.к. на экране присутствуют два `RecyclerView` , то им требуется два разных объекта `TrackAdapter`. У каждого адаптера свой набор треков, не связанный с другим адаптером. Поэтому нет необходимости внутри `TrackAdapter` хранить два списка треков для истории и для поиска. Просто мы будем понимать, адаптер истории будет хранить в себе в поле `tracks` список треков из истории поиска, а адаптер поиска - список треков результата поиска

2023-04-07 01:03 UTC, kirillNay commented on app/src/main/res/layout/activity_search.xml
> +                android:text="Вы искали"
⏫ Кажется забыл применить текст из ресурсов - `search_history_message`

2023-04-07 01:03 UTC, NoDopezzz commented on app/src/main/res/layout/track_item.xml
> +    android:background="?android:attr/selectableItemBackground">
👍 Отличная идея применить `selectableItemBackground`! Теперь при нажатии на треки можно увидеть ripple эффект!

2023-04-07 01:03 UTC, NoDopezzz commented on app/src/main/res/layout/activity_search.xml
> +                android:paddingTop="@dimen/padding_24"/>
⚠️ Для горизонтальных падингов применен текстовый размер - `16sp`

2023-04-07 12:53 UTC, agolyud commented
Доработал недочеты

2023-04-08 01:44 UTC, NoDopezzz approved these changes

2023-04-10 07:55 UTC, merged